add method and utest implemented
Glebzok/FSE_Lab_Version_Control pull request #3
Opened 2020-10-03 11:53 UTC by NicholasSk

2020-10-03 12:13 UTC, Glebzok requested changes
could you please delete the line where you import unittest, you didn't use it anywhere

2020-10-05 12:53 UTC, Glebzok approved these changes
everything is good now

2020-10-05 12:55 UTC, Allessyer commented
Everything is good.

2020-10-05 13:22 UTC, Allessyer approved these changes
Everything is good.

2020-10-05 13:26 UTC, merged